// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "gozero-user-demo/internal/handler/auth"
	user "gozero-user-demo/internal/handler/user"
	"gozero-user-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Audit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Audit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/me",
					Handler: user.GetMeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:userId",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/users/me",
					Handler: user.UpdateProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/users/me/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
