// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type EmptyResp struct{}

type UserProfile struct {
	Id        int64  `json:"id"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	Bio       string `json:"bio"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"createdAt"`
}

type UserResp struct {
	User UserProfile `json:"user"`
}

type GetUserReq struct {
	UserId int64 `path:"userId"`
}

type UpdateProfileReq struct {
	Nickname *string `json:"nickname,optional"`
	Bio      *string `json:"bio,optional"`
	Avatar   *string `json:"avatar,optional"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}
