// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken   string `json:"accessToken"`
	AccessExpire  int64  `json:"accessExpire"`
	RefreshToken  string `json:"refreshToken"`
	RefreshExpire int64  `json:"refreshExpire"`
}

type EmptyResp struct {
}

type UserProfile struct {
	Id        int64  `json:"id"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	Bio       string `json:"bio"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"createdAt"`
}

type UserResp struct {
	User UserProfile `json:"user"`
}

type GetUserReq struct {
	UserId int64 `path:"userId"`
}

type ListUsersReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type UpdateProfileReq struct {
	Nickname *string `json:"nickname,optional"`
	Bio      *string `json:"bio,optional"`
	Avatar   *string `json:"avatar,optional"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type UserListResp struct {
	Items    []UserProfile `json:"items"`
	Page     int64         `json:"page"`
	PageSize int64         `json:"pageSize"`
	Total    int64         `json:"total"`
}
